// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.access-request.requester@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const REQUESTER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const REQUESTER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_requester { () => { "{\"capability_id\":\"lenso.access-request.requester@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"cancel\",\"create\",\"get\",\"list\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_requester_client { () => { "{\"capability_id\":\"lenso.access-request.requester@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_requester_client { () => { "{\"capability_id\":\"lenso.access-request.requester@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CANCEL_OPERATION: &str = "cancel";
pub const CREATE_OPERATION: &str = "create";
pub const GET_OPERATION: &str = "get";
pub const LIST_OPERATION: &str = "list";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CancelRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CancelResponse {
    #[serde(rename = "bundle_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub bundle_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "decided_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decided_by: Option<String>,
    #[serde(rename = "decision_note")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decision_note: Option<String>,
    #[serde(rename = "effect_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_status: CancelResponseEffectStatus,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "requester_was_member")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_was_member: bool,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "role")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role: CancelResponseRole,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: CancelResponseScope,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: CancelResponseStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for CancelResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CancelResponse")
            .field("bundle_id", &self.bundle_id)
            .field("created_at", &self.created_at)
            .field("decided_by", &self.decided_by)
            .field("decision_note", &"<redacted>")
            .field("effect_status", &self.effect_status)
            .field("expires_at", &self.expires_at)
            .field("organization_id", &self.organization_id)
            .field("permissions", &self.permissions)
            .field("reason", &"<redacted>")
            .field("request_id", &self.request_id)
            .field("requester_subject", &self.requester_subject)
            .field("requester_was_member", &self.requester_was_member)
            .field("revision", &self.revision)
            .field("role", &self.role)
            .field("scope", &self.scope)
            .field("status", &self.status)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CancelResponseEffectStatus {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "leased")]
    Leased,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CancelResponseRole {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: String,
    #[serde(rename = "mode")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mode: CancelResponseRoleMode,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CancelResponseRoleMode {
    #[serde(rename = "existing")]
    Existing,
    #[serde(rename = "managed")]
    Managed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CancelResponseScope {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CancelResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "intervention_required")]
    InterventionRequired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CancelError {
    AccessAlreadyGranted,
    ActiveRequestConflict,
    BundleNotRequestable,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OrganizationNotFound,
    RequestExpired,
    RequestNotFound,
    RevisionConflict,
    ScopeNotRequestable,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRequest {
    #[serde(rename = "bundle_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub bundle_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "recipient")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub recipient: CreateRequestRecipient,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: CreateRequestScope,
}

impl fmt::Debug for CreateRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CreateRequest")
            .field("bundle_id", &self.bundle_id)
            .field("expires_at", &self.expires_at)
            .field("idempotency_key", &self.idempotency_key)
            .field("organization_id", &self.organization_id)
            .field("reason", &"<redacted>")
            .field("recipient", &self.recipient)
            .field("scope", &self.scope)
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRequestRecipient {
    #[serde(rename = "address")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub address: String,
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: Option<String>,
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: CreateRequestRecipientLocale,
}

impl fmt::Debug for CreateRequestRecipient {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CreateRequestRecipient")
            .field("address", &"<redacted>")
            .field("display_name", &"<redacted>")
            .field("locale", &self.locale)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateRequestRecipientLocale {
    #[serde(rename = "en")]
    En,
    #[serde(rename = "en-US")]
    EnUS,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRequestScope {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "merged")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub merged: bool,
    #[serde(rename = "request")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request: CreateResponseRequest,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateResponseRequest {
    #[serde(rename = "bundle_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub bundle_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "decided_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decided_by: Option<String>,
    #[serde(rename = "decision_note")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decision_note: Option<String>,
    #[serde(rename = "effect_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_status: CreateResponseRequestEffectStatus,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "requester_was_member")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_was_member: bool,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "role")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role: CreateResponseRequestRole,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: CreateResponseRequestScope,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: CreateResponseRequestStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for CreateResponseRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CreateResponseRequest")
            .field("bundle_id", &self.bundle_id)
            .field("created_at", &self.created_at)
            .field("decided_by", &self.decided_by)
            .field("decision_note", &"<redacted>")
            .field("effect_status", &self.effect_status)
            .field("expires_at", &self.expires_at)
            .field("organization_id", &self.organization_id)
            .field("permissions", &self.permissions)
            .field("reason", &"<redacted>")
            .field("request_id", &self.request_id)
            .field("requester_subject", &self.requester_subject)
            .field("requester_was_member", &self.requester_was_member)
            .field("revision", &self.revision)
            .field("role", &self.role)
            .field("scope", &self.scope)
            .field("status", &self.status)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateResponseRequestEffectStatus {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "leased")]
    Leased,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateResponseRequestRole {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: String,
    #[serde(rename = "mode")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mode: CreateResponseRequestRoleMode,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateResponseRequestRoleMode {
    #[serde(rename = "existing")]
    Existing,
    #[serde(rename = "managed")]
    Managed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateResponseRequestScope {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateResponseRequestStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "intervention_required")]
    InterventionRequired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateError {
    AccessAlreadyGranted,
    ActiveRequestConflict,
    BundleNotRequestable,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OrganizationNotFound,
    RequestExpired,
    RequestNotFound,
    RevisionConflict,
    ScopeNotRequestable,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequest {
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetResponse {
    #[serde(rename = "bundle_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub bundle_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "decided_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decided_by: Option<String>,
    #[serde(rename = "decision_note")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decision_note: Option<String>,
    #[serde(rename = "effect_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_status: GetResponseEffectStatus,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "requester_was_member")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_was_member: bool,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "role")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role: GetResponseRole,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: GetResponseScope,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: GetResponseStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for GetResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GetResponse")
            .field("bundle_id", &self.bundle_id)
            .field("created_at", &self.created_at)
            .field("decided_by", &self.decided_by)
            .field("decision_note", &"<redacted>")
            .field("effect_status", &self.effect_status)
            .field("expires_at", &self.expires_at)
            .field("organization_id", &self.organization_id)
            .field("permissions", &self.permissions)
            .field("reason", &"<redacted>")
            .field("request_id", &self.request_id)
            .field("requester_subject", &self.requester_subject)
            .field("requester_was_member", &self.requester_was_member)
            .field("revision", &self.revision)
            .field("role", &self.role)
            .field("scope", &self.scope)
            .field("status", &self.status)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetResponseEffectStatus {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "leased")]
    Leased,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetResponseRole {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: String,
    #[serde(rename = "mode")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mode: GetResponseRoleMode,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetResponseRoleMode {
    #[serde(rename = "existing")]
    Existing,
    #[serde(rename = "managed")]
    Managed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetResponseScope {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "intervention_required")]
    InterventionRequired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetError {
    AccessAlreadyGranted,
    ActiveRequestConflict,
    BundleNotRequestable,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OrganizationNotFound,
    RequestExpired,
    RequestNotFound,
    RevisionConflict,
    ScopeNotRequestable,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequest {
    #[serde(rename = "cursor")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "status")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ListRequestStatus>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListRequestStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "intervention_required")]
    InterventionRequired,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListResponse {
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "requests")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requests: Vec<ListResponseRequestsItem>,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListResponseRequestsItem {
    #[serde(rename = "bundle_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub bundle_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "decided_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decided_by: Option<String>,
    #[serde(rename = "decision_note")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decision_note: Option<String>,
    #[serde(rename = "effect_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_status: ListResponseRequestsItemEffectStatus,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "permissions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permissions: Vec<String>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "requester_was_member")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_was_member: bool,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "role")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role: ListResponseRequestsItemRole,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: ListResponseRequestsItemScope,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ListResponseRequestsItemStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for ListResponseRequestsItem {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ListResponseRequestsItem")
            .field("bundle_id", &self.bundle_id)
            .field("created_at", &self.created_at)
            .field("decided_by", &self.decided_by)
            .field("decision_note", &"<redacted>")
            .field("effect_status", &self.effect_status)
            .field("expires_at", &self.expires_at)
            .field("organization_id", &self.organization_id)
            .field("permissions", &self.permissions)
            .field("reason", &"<redacted>")
            .field("request_id", &self.request_id)
            .field("requester_subject", &self.requester_subject)
            .field("requester_was_member", &self.requester_was_member)
            .field("revision", &self.revision)
            .field("role", &self.role)
            .field("scope", &self.scope)
            .field("status", &self.status)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListResponseRequestsItemEffectStatus {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "leased")]
    Leased,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListResponseRequestsItemRole {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: String,
    #[serde(rename = "mode")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mode: ListResponseRequestsItemRoleMode,
    #[serde(rename = "role_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListResponseRequestsItemRoleMode {
    #[serde(rename = "existing")]
    Existing,
    #[serde(rename = "managed")]
    Managed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListResponseRequestsItemScope {
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListResponseRequestsItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "intervention_required")]
    InterventionRequired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListError {
    AccessAlreadyGranted,
    ActiveRequestConflict,
    BundleNotRequestable,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OrganizationNotFound,
    RequestExpired,
    RequestNotFound,
    RevisionConflict,
    ScopeNotRequestable,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct RequesterCancel;
impl RequestCapability for RequesterCancel {
    type Request = CancelRequest;
    type Response = CancelResponse;
    type DomainError = CancelError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CANCEL_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<RequesterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).cancel(context, request)
    }
}

#[derive(Debug)]
pub struct RequesterCreate;
impl RequestCapability for RequesterCreate {
    type Request = CreateRequest;
    type Response = CreateResponse;
    type DomainError = CreateError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<RequesterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create(context, request)
    }
}

#[derive(Debug)]
pub struct RequesterGet;
impl RequestCapability for RequesterGet {
    type Request = GetRequest;
    type Response = GetResponse;
    type DomainError = GetError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<RequesterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get(context, request)
    }
}

#[derive(Debug)]
pub struct RequesterList;
impl RequestCapability for RequesterList {
    type Request = ListRequest;
    type Response = ListResponse;
    type DomainError = ListError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<RequesterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list(context, request)
    }
}

impl serde::Serialize for CancelError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessAlreadyGranted => serializer.serialize_str("access_already_granted"),
            Self::ActiveRequestConflict => serializer.serialize_str("active_request_conflict"),
            Self::BundleNotRequestable => serializer.serialize_str("bundle_not_requestable"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RequestExpired => serializer.serialize_str("request_expired"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeNotRequestable => serializer.serialize_str("scope_not_requestable"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CancelError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_already_granted" => Ok(Self::AccessAlreadyGranted),
                "active_request_conflict" => Ok(Self::ActiveRequestConflict),
                "bundle_not_requestable" => Ok(Self::BundleNotRequestable),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "request_expired" => Ok(Self::RequestExpired),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_not_requestable" => Ok(Self::ScopeNotRequestable),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CreateError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessAlreadyGranted => serializer.serialize_str("access_already_granted"),
            Self::ActiveRequestConflict => serializer.serialize_str("active_request_conflict"),
            Self::BundleNotRequestable => serializer.serialize_str("bundle_not_requestable"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RequestExpired => serializer.serialize_str("request_expired"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeNotRequestable => serializer.serialize_str("scope_not_requestable"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_already_granted" => Ok(Self::AccessAlreadyGranted),
                "active_request_conflict" => Ok(Self::ActiveRequestConflict),
                "bundle_not_requestable" => Ok(Self::BundleNotRequestable),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "request_expired" => Ok(Self::RequestExpired),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_not_requestable" => Ok(Self::ScopeNotRequestable),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessAlreadyGranted => serializer.serialize_str("access_already_granted"),
            Self::ActiveRequestConflict => serializer.serialize_str("active_request_conflict"),
            Self::BundleNotRequestable => serializer.serialize_str("bundle_not_requestable"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RequestExpired => serializer.serialize_str("request_expired"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeNotRequestable => serializer.serialize_str("scope_not_requestable"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_already_granted" => Ok(Self::AccessAlreadyGranted),
                "active_request_conflict" => Ok(Self::ActiveRequestConflict),
                "bundle_not_requestable" => Ok(Self::BundleNotRequestable),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "request_expired" => Ok(Self::RequestExpired),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_not_requestable" => Ok(Self::ScopeNotRequestable),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessAlreadyGranted => serializer.serialize_str("access_already_granted"),
            Self::ActiveRequestConflict => serializer.serialize_str("active_request_conflict"),
            Self::BundleNotRequestable => serializer.serialize_str("bundle_not_requestable"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RequestExpired => serializer.serialize_str("request_expired"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::ScopeNotRequestable => serializer.serialize_str("scope_not_requestable"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_already_granted" => Ok(Self::AccessAlreadyGranted),
                "active_request_conflict" => Ok(Self::ActiveRequestConflict),
                "bundle_not_requestable" => Ok(Self::BundleNotRequestable),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "request_expired" => Ok(Self::RequestExpired),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "scope_not_requestable" => Ok(Self::ScopeNotRequestable),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_cancel_request(value: &CancelRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_cancel_request(wire: &str) -> Result<CancelRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_cancel_response(value: &CancelResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_cancel_response(wire: &str) -> Result<CancelResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_cancel_error(value: &CancelError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_cancel_error(wire: &str) -> Result<CancelError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_create_request(value: &CreateRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_request(wire: &str) -> Result<CreateRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_response(value: &CreateResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_response(wire: &str) -> Result<CreateResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_error(value: &CreateError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_error(wire: &str) -> Result<CreateError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_request(value: &GetRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_request(wire: &str) -> Result<GetRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_response(value: &GetResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_response(wire: &str) -> Result<GetResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_error(value: &GetError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_error(wire: &str) -> Result<GetError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_request(value: &ListRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_request(wire: &str) -> Result<ListRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_response(value: &ListResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_response(wire: &str) -> Result<ListResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_error(value: &ListError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_error(wire: &str) -> Result<ListError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoRequesterCancelResult {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure>;
}
impl __LensoIntoRequesterCancelResult for Result<CancelResponse, CancelError> {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoRequesterCancelResult for Result<Result<CancelResponse, CancelError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure> { self }
}
impl __LensoIntoRequesterCancelResult for Result<CancelResponse, lenso_plugin_authoring::PluginError<CancelError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoRequesterCancelResult for Result<CancelResponse, RequesterCancelInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(RequesterCancelInvocationError::Domain(error)) => Ok(Err(error)),
            Err(RequesterCancelInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoRequesterCreateResult {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure>;
}
impl __LensoIntoRequesterCreateResult for Result<CreateResponse, CreateError> {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoRequesterCreateResult for Result<Result<CreateResponse, CreateError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure> { self }
}
impl __LensoIntoRequesterCreateResult for Result<CreateResponse, lenso_plugin_authoring::PluginError<CreateError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoRequesterCreateResult for Result<CreateResponse, RequesterCreateInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateResponse, CreateError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(RequesterCreateInvocationError::Domain(error)) => Ok(Err(error)),
            Err(RequesterCreateInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoRequesterGetResult {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure>;
}
impl __LensoIntoRequesterGetResult for Result<GetResponse, GetError> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoRequesterGetResult for Result<Result<GetResponse, GetError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> { self }
}
impl __LensoIntoRequesterGetResult for Result<GetResponse, lenso_plugin_authoring::PluginError<GetError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoRequesterGetResult for Result<GetResponse, RequesterGetInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(RequesterGetInvocationError::Domain(error)) => Ok(Err(error)),
            Err(RequesterGetInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoRequesterListResult {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure>;
}
impl __LensoIntoRequesterListResult for Result<ListResponse, ListError> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoRequesterListResult for Result<Result<ListResponse, ListError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> { self }
}
impl __LensoIntoRequesterListResult for Result<ListResponse, lenso_plugin_authoring::PluginError<ListError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoRequesterListResult for Result<ListResponse, RequesterListInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListResponse, ListError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(RequesterListInvocationError::Domain(error)) => Ok(Err(error)),
            Err(RequesterListInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait RequesterProvider: fmt::Debug + 'static {
    fn cancel(&self, context: InvocationContext, request: CancelRequest) -> NativeRequestFuture<RequesterCancel>;
    fn create(&self, context: InvocationContext, request: CreateRequest) -> NativeRequestFuture<RequesterCreate>;
    fn get(&self, context: InvocationContext, request: GetRequest) -> NativeRequestFuture<RequesterGet>;
    fn list(&self, context: InvocationContext, request: ListRequest) -> NativeRequestFuture<RequesterList>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_requester {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportRequester;
        impl $crate::RequesterProvider for $plugin {
        fn cancel(&self, context: __LensoNativeSupportRequester::InvocationContext, request: $crate::CancelRequest) -> __LensoNativeSupportRequester::NativeRequestFuture<$crate::RequesterCancel> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::cancel(&plugin, context, request).await;
                $crate::__LensoIntoRequesterCancelResult::__lenso_into_result(result)
            })
        }
        fn create(&self, context: __LensoNativeSupportRequester::InvocationContext, request: $crate::CreateRequest) -> __LensoNativeSupportRequester::NativeRequestFuture<$crate::RequesterCreate> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create(&plugin, context, request).await;
                $crate::__LensoIntoRequesterCreateResult::__lenso_into_result(result)
            })
        }
        fn get(&self, context: __LensoNativeSupportRequester::InvocationContext, request: $crate::GetRequest) -> __LensoNativeSupportRequester::NativeRequestFuture<$crate::RequesterGet> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get(&plugin, context, request).await;
                $crate::__LensoIntoRequesterGetResult::__lenso_into_result(result)
            })
        }
        fn list(&self, context: __LensoNativeSupportRequester::InvocationContext, request: $crate::ListRequest) -> __LensoNativeSupportRequester::NativeRequestFuture<$crate::RequesterList> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list(&plugin, context, request).await;
                $crate::__LensoIntoRequesterListResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct RequesterRequestEndpoint { provider: Rc<dyn RequesterProvider> }

#[derive(Debug)]
pub struct RequesterEndpoint<P: RequesterProvider> { provider: Rc<P>, request_endpoint: RequesterRequestEndpoint }
impl<P: RequesterProvider> RequesterEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn RequesterProvider> = provider.clone();
        Self { provider, request_endpoint: RequesterRequestEndpoint { provider: request_provider } }
    }
}

impl<P: RequesterProvider> NativeRequestEndpoint for RequesterEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CANCEL_OPERATION,
        CREATE_OPERATION,
        GET_OPERATION,
        LIST_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CANCEL_OPERATION => {
                let Ok(request) = request.downcast::<CancelRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).cancel(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            CREATE_OPERATION => {
                let Ok(request) = request.downcast::<CreateRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_OPERATION => {
                let Ok(request) = request.downcast::<GetRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_OPERATION => {
                let Ok(request) = request.downcast::<ListRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_requester {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::RequesterEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_requester {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_requester!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct RequesterClient {
    cancel: NativeRequestHandle<RequesterCancel>,
    create: NativeRequestHandle<RequesterCreate>,
    get: NativeRequestHandle<RequesterGet>,
    list: NativeRequestHandle<RequesterList>,
}
impl RequesterClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn cancel(&self, request: CancelRequest) -> Result<CancelResponse, RequesterCancelInvocationError> {
        self.cancel.invoke(CANCEL_OPERATION, request).await
            .map_err(RequesterCancelInvocationError::Runtime)?
            .map_err(RequesterCancelInvocationError::Domain)
    }

    pub async fn cancel_with_context(&self, context: InvocationContext, request: CancelRequest) -> Result<CancelResponse, RequesterCancelInvocationError> {
        self.cancel.invoke_with_context(CANCEL_OPERATION, context, request).await
            .map_err(RequesterCancelInvocationError::Runtime)?
            .map_err(RequesterCancelInvocationError::Domain)
    }

    pub async fn create(&self, request: CreateRequest) -> Result<CreateResponse, RequesterCreateInvocationError> {
        self.create.invoke(CREATE_OPERATION, request).await
            .map_err(RequesterCreateInvocationError::Runtime)?
            .map_err(RequesterCreateInvocationError::Domain)
    }

    pub async fn create_with_context(&self, context: InvocationContext, request: CreateRequest) -> Result<CreateResponse, RequesterCreateInvocationError> {
        self.create.invoke_with_context(CREATE_OPERATION, context, request).await
            .map_err(RequesterCreateInvocationError::Runtime)?
            .map_err(RequesterCreateInvocationError::Domain)
    }

    pub async fn get(&self, request: GetRequest) -> Result<GetResponse, RequesterGetInvocationError> {
        self.get.invoke(GET_OPERATION, request).await
            .map_err(RequesterGetInvocationError::Runtime)?
            .map_err(RequesterGetInvocationError::Domain)
    }

    pub async fn get_with_context(&self, context: InvocationContext, request: GetRequest) -> Result<GetResponse, RequesterGetInvocationError> {
        self.get.invoke_with_context(GET_OPERATION, context, request).await
            .map_err(RequesterGetInvocationError::Runtime)?
            .map_err(RequesterGetInvocationError::Domain)
    }

    pub async fn list(&self, request: ListRequest) -> Result<ListResponse, RequesterListInvocationError> {
        self.list.invoke(LIST_OPERATION, request).await
            .map_err(RequesterListInvocationError::Runtime)?
            .map_err(RequesterListInvocationError::Domain)
    }

    pub async fn list_with_context(&self, context: InvocationContext, request: ListRequest) -> Result<ListResponse, RequesterListInvocationError> {
        self.list.invoke_with_context(LIST_OPERATION, context, request).await
            .map_err(RequesterListInvocationError::Runtime)?
            .map_err(RequesterListInvocationError::Domain)
    }
}

impl CapabilityClient for RequesterClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            cancel: dependencies.one::<RequesterCancel>()?,
            create: dependencies.one::<RequesterCreate>()?,
            get: dependencies.one::<RequesterGet>()?,
            list: dependencies.one::<RequesterList>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for RequesterClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    cancel: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<RequesterCancel>()?,
                    create: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<RequesterCreate>()?,
                    get: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<RequesterGet>()?,
                    list: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<RequesterList>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum RequesterCancelInvocationError {
    Domain(CancelError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum RequesterCreateInvocationError {
    Domain(CreateError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum RequesterGetInvocationError {
    Domain(GetError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum RequesterListInvocationError {
    Domain(ListError),
    Runtime(RuntimeFailure),
}
