// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.access-request.worker@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const WORKER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const WORKER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_worker { () => { "{\"capability_id\":\"lenso.access-request.worker@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"claim_due\",\"expire\",\"process\",\"retry\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_worker_client { () => { "{\"capability_id\":\"lenso.access-request.worker@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_worker_client { () => { "{\"capability_id\":\"lenso.access-request.worker@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CLAIM_DUE_OPERATION: &str = "claim_due";
pub const EXPIRE_OPERATION: &str = "expire";
pub const PROCESS_OPERATION: &str = "process";
pub const RETRY_OPERATION: &str = "retry";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimDueRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "lease_seconds")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_seconds: i64,
    #[serde(rename = "worker_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub worker_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimDueResponse {
    #[serde(rename = "job")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job: Option<ClaimDueResponseJob>,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimDueResponseJob {
    #[serde(rename = "fence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub fence: String,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ClaimDueResponseJobKind,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
    #[serde(rename = "lease_until")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_until: Timestamp,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

impl fmt::Debug for ClaimDueResponseJob {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ClaimDueResponseJob")
            .field("fence", &self.fence)
            .field("job_id", &self.job_id)
            .field("kind", &self.kind)
            .field("lease_token", &"<redacted>")
            .field("lease_until", &self.lease_until)
            .field("organization_id", &self.organization_id)
            .field("request_id", &self.request_id)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ClaimDueResponseJobKind {
    #[serde(rename = "access_effect")]
    AccessEffect,
    #[serde(rename = "notification")]
    Notification,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ClaimDueError {
    EffectNotFound,
    EffectUnknown,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    LeaseLost,
    OperationInProgress,
    RequestNotExpired,
    RequestNotFound,
    RetryNotAllowed,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExpireRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExpireResponse {
    #[serde(rename = "automatic_retry_allowed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub automatic_retry_allowed: bool,
    #[serde(rename = "job_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_status: ExpireResponseJobStatus,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "request_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_revision: String,
    #[serde(rename = "request_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_status: ExpireResponseRequestStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ExpireResponseJobStatus {
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ExpireResponseRequestStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "intervention_required")]
    InterventionRequired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExpireError {
    EffectNotFound,
    EffectUnknown,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    LeaseLost,
    OperationInProgress,
    RequestNotExpired,
    RequestNotFound,
    RetryNotAllowed,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessRequest {
    #[serde(rename = "fence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub fence: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
}

impl fmt::Debug for ProcessRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ProcessRequest")
            .field("fence", &self.fence)
            .field("idempotency_key", &self.idempotency_key)
            .field("job_id", &self.job_id)
            .field("lease_token", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessResponse {
    #[serde(rename = "automatic_retry_allowed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub automatic_retry_allowed: bool,
    #[serde(rename = "job_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_status: ProcessResponseJobStatus,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "request_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_revision: String,
    #[serde(rename = "request_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_status: ProcessResponseRequestStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ProcessResponseJobStatus {
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ProcessResponseRequestStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "intervention_required")]
    InterventionRequired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProcessError {
    EffectNotFound,
    EffectUnknown,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    LeaseLost,
    OperationInProgress,
    RequestNotExpired,
    RequestNotFound,
    RetryNotAllowed,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryRequest {
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "expected_effect_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_effect_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryResponse {
    #[serde(rename = "attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempts: i64,
    #[serde(rename = "automatic_retry_allowed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub automatic_retry_allowed: bool,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "error_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub error_code: Option<String>,
    #[serde(rename = "evidence_reference")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub evidence_reference: Option<String>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: RetryResponseKind,
    #[serde(rename = "lease_until")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_until: Option<Timestamp>,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "sequence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sequence: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RetryResponseStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryResponseKind {
    #[serde(rename = "create_role")]
    CreateRole,
    #[serde(rename = "set_role_permissions")]
    SetRolePermissions,
    #[serde(rename = "assign_role")]
    AssignRole,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "leased")]
    Leased,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RetryError {
    EffectNotFound,
    EffectUnknown,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    LeaseLost,
    OperationInProgress,
    RequestNotExpired,
    RequestNotFound,
    RetryNotAllowed,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct WorkerClaimDue;
impl RequestCapability for WorkerClaimDue {
    type Request = ClaimDueRequest;
    type Response = ClaimDueResponse;
    type DomainError = ClaimDueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CLAIM_DUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<WorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).claim_due(context, request)
    }
}

#[derive(Debug)]
pub struct WorkerExpire;
impl RequestCapability for WorkerExpire {
    type Request = ExpireRequest;
    type Response = ExpireResponse;
    type DomainError = ExpireError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXPIRE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<WorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).expire(context, request)
    }
}

#[derive(Debug)]
pub struct WorkerProcess;
impl RequestCapability for WorkerProcess {
    type Request = ProcessRequest;
    type Response = ProcessResponse;
    type DomainError = ProcessError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PROCESS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<WorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).process(context, request)
    }
}

#[derive(Debug)]
pub struct WorkerRetry;
impl RequestCapability for WorkerRetry {
    type Request = RetryRequest;
    type Response = RetryResponse;
    type DomainError = RetryError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RETRY_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<WorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).retry(context, request)
    }
}

impl serde::Serialize for ClaimDueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::EffectNotFound => serializer.serialize_str("effect_not_found"),
            Self::EffectUnknown => serializer.serialize_str("effect_unknown"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::LeaseLost => serializer.serialize_str("lease_lost"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotExpired => serializer.serialize_str("request_not_expired"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RetryNotAllowed => serializer.serialize_str("retry_not_allowed"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ClaimDueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "effect_not_found" => Ok(Self::EffectNotFound),
                "effect_unknown" => Ok(Self::EffectUnknown),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "lease_lost" => Ok(Self::LeaseLost),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_expired" => Ok(Self::RequestNotExpired),
                "request_not_found" => Ok(Self::RequestNotFound),
                "retry_not_allowed" => Ok(Self::RetryNotAllowed),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ExpireError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::EffectNotFound => serializer.serialize_str("effect_not_found"),
            Self::EffectUnknown => serializer.serialize_str("effect_unknown"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::LeaseLost => serializer.serialize_str("lease_lost"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotExpired => serializer.serialize_str("request_not_expired"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RetryNotAllowed => serializer.serialize_str("retry_not_allowed"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExpireError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "effect_not_found" => Ok(Self::EffectNotFound),
                "effect_unknown" => Ok(Self::EffectUnknown),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "lease_lost" => Ok(Self::LeaseLost),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_expired" => Ok(Self::RequestNotExpired),
                "request_not_found" => Ok(Self::RequestNotFound),
                "retry_not_allowed" => Ok(Self::RetryNotAllowed),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ProcessError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::EffectNotFound => serializer.serialize_str("effect_not_found"),
            Self::EffectUnknown => serializer.serialize_str("effect_unknown"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::LeaseLost => serializer.serialize_str("lease_lost"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotExpired => serializer.serialize_str("request_not_expired"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RetryNotAllowed => serializer.serialize_str("retry_not_allowed"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ProcessError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "effect_not_found" => Ok(Self::EffectNotFound),
                "effect_unknown" => Ok(Self::EffectUnknown),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "lease_lost" => Ok(Self::LeaseLost),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_expired" => Ok(Self::RequestNotExpired),
                "request_not_found" => Ok(Self::RequestNotFound),
                "retry_not_allowed" => Ok(Self::RetryNotAllowed),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RetryError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::EffectNotFound => serializer.serialize_str("effect_not_found"),
            Self::EffectUnknown => serializer.serialize_str("effect_unknown"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::LeaseLost => serializer.serialize_str("lease_lost"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotExpired => serializer.serialize_str("request_not_expired"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RetryNotAllowed => serializer.serialize_str("retry_not_allowed"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RetryError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "effect_not_found" => Ok(Self::EffectNotFound),
                "effect_unknown" => Ok(Self::EffectUnknown),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "lease_lost" => Ok(Self::LeaseLost),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_expired" => Ok(Self::RequestNotExpired),
                "request_not_found" => Ok(Self::RequestNotFound),
                "retry_not_allowed" => Ok(Self::RetryNotAllowed),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_claim_due_request(value: &ClaimDueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_due_request(wire: &str) -> Result<ClaimDueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_due_response(value: &ClaimDueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_due_response(wire: &str) -> Result<ClaimDueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_due_error(value: &ClaimDueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_due_error(wire: &str) -> Result<ClaimDueError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_expire_request(value: &ExpireRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_request(wire: &str) -> Result<ExpireRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_expire_response(value: &ExpireResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_response(wire: &str) -> Result<ExpireResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_expire_error(value: &ExpireError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_error(wire: &str) -> Result<ExpireError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_process_request(value: &ProcessRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_request(wire: &str) -> Result<ProcessRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_process_response(value: &ProcessResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_response(wire: &str) -> Result<ProcessResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_process_error(value: &ProcessError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_error(wire: &str) -> Result<ProcessError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_retry_request(value: &RetryRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_request(wire: &str) -> Result<RetryRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_retry_response(value: &RetryResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_response(wire: &str) -> Result<RetryResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_retry_error(value: &RetryError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_error(wire: &str) -> Result<RetryError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoWorkerClaimDueResult {
    fn __lenso_into_result(self) -> Result<Result<ClaimDueResponse, ClaimDueError>, RuntimeFailure>;
}
impl __LensoIntoWorkerClaimDueResult for Result<ClaimDueResponse, ClaimDueError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimDueResponse, ClaimDueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoWorkerClaimDueResult for Result<Result<ClaimDueResponse, ClaimDueError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ClaimDueResponse, ClaimDueError>, RuntimeFailure> { self }
}
impl __LensoIntoWorkerClaimDueResult for Result<ClaimDueResponse, lenso_plugin_authoring::PluginError<ClaimDueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ClaimDueResponse, ClaimDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoWorkerClaimDueResult for Result<ClaimDueResponse, WorkerClaimDueInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimDueResponse, ClaimDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(WorkerClaimDueInvocationError::Domain(error)) => Ok(Err(error)),
            Err(WorkerClaimDueInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoWorkerExpireResult {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure>;
}
impl __LensoIntoWorkerExpireResult for Result<ExpireResponse, ExpireError> {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoWorkerExpireResult for Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> { self }
}
impl __LensoIntoWorkerExpireResult for Result<ExpireResponse, lenso_plugin_authoring::PluginError<ExpireError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoWorkerExpireResult for Result<ExpireResponse, WorkerExpireInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(WorkerExpireInvocationError::Domain(error)) => Ok(Err(error)),
            Err(WorkerExpireInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoWorkerProcessResult {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure>;
}
impl __LensoIntoWorkerProcessResult for Result<ProcessResponse, ProcessError> {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoWorkerProcessResult for Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> { self }
}
impl __LensoIntoWorkerProcessResult for Result<ProcessResponse, lenso_plugin_authoring::PluginError<ProcessError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoWorkerProcessResult for Result<ProcessResponse, WorkerProcessInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(WorkerProcessInvocationError::Domain(error)) => Ok(Err(error)),
            Err(WorkerProcessInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoWorkerRetryResult {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure>;
}
impl __LensoIntoWorkerRetryResult for Result<RetryResponse, RetryError> {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoWorkerRetryResult for Result<Result<RetryResponse, RetryError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure> { self }
}
impl __LensoIntoWorkerRetryResult for Result<RetryResponse, lenso_plugin_authoring::PluginError<RetryError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoWorkerRetryResult for Result<RetryResponse, WorkerRetryInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RetryResponse, RetryError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(WorkerRetryInvocationError::Domain(error)) => Ok(Err(error)),
            Err(WorkerRetryInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait WorkerProvider: fmt::Debug + 'static {
    fn claim_due(&self, context: InvocationContext, request: ClaimDueRequest) -> NativeRequestFuture<WorkerClaimDue>;
    fn expire(&self, context: InvocationContext, request: ExpireRequest) -> NativeRequestFuture<WorkerExpire>;
    fn process(&self, context: InvocationContext, request: ProcessRequest) -> NativeRequestFuture<WorkerProcess>;
    fn retry(&self, context: InvocationContext, request: RetryRequest) -> NativeRequestFuture<WorkerRetry>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_worker {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportWorker;
        impl $crate::WorkerProvider for $plugin {
        fn claim_due(&self, context: __LensoNativeSupportWorker::InvocationContext, request: $crate::ClaimDueRequest) -> __LensoNativeSupportWorker::NativeRequestFuture<$crate::WorkerClaimDue> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::claim_due(&plugin, context, request).await;
                $crate::__LensoIntoWorkerClaimDueResult::__lenso_into_result(result)
            })
        }
        fn expire(&self, context: __LensoNativeSupportWorker::InvocationContext, request: $crate::ExpireRequest) -> __LensoNativeSupportWorker::NativeRequestFuture<$crate::WorkerExpire> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::expire(&plugin, context, request).await;
                $crate::__LensoIntoWorkerExpireResult::__lenso_into_result(result)
            })
        }
        fn process(&self, context: __LensoNativeSupportWorker::InvocationContext, request: $crate::ProcessRequest) -> __LensoNativeSupportWorker::NativeRequestFuture<$crate::WorkerProcess> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::process(&plugin, context, request).await;
                $crate::__LensoIntoWorkerProcessResult::__lenso_into_result(result)
            })
        }
        fn retry(&self, context: __LensoNativeSupportWorker::InvocationContext, request: $crate::RetryRequest) -> __LensoNativeSupportWorker::NativeRequestFuture<$crate::WorkerRetry> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::retry(&plugin, context, request).await;
                $crate::__LensoIntoWorkerRetryResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct WorkerRequestEndpoint { provider: Rc<dyn WorkerProvider> }

#[derive(Debug)]
pub struct WorkerEndpoint<P: WorkerProvider> { provider: Rc<P>, request_endpoint: WorkerRequestEndpoint }
impl<P: WorkerProvider> WorkerEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn WorkerProvider> = provider.clone();
        Self { provider, request_endpoint: WorkerRequestEndpoint { provider: request_provider } }
    }
}

impl<P: WorkerProvider> NativeRequestEndpoint for WorkerEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CLAIM_DUE_OPERATION,
        EXPIRE_OPERATION,
        PROCESS_OPERATION,
        RETRY_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CLAIM_DUE_OPERATION => {
                let Ok(request) = request.downcast::<ClaimDueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).claim_due(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            EXPIRE_OPERATION => {
                let Ok(request) = request.downcast::<ExpireRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).expire(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            PROCESS_OPERATION => {
                let Ok(request) = request.downcast::<ProcessRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).process(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RETRY_OPERATION => {
                let Ok(request) = request.downcast::<RetryRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).retry(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_worker {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::WorkerEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_worker {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_worker!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct WorkerClient {
    claim_due: NativeRequestHandle<WorkerClaimDue>,
    expire: NativeRequestHandle<WorkerExpire>,
    process: NativeRequestHandle<WorkerProcess>,
    retry: NativeRequestHandle<WorkerRetry>,
}
impl WorkerClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn claim_due(&self, request: ClaimDueRequest) -> Result<ClaimDueResponse, WorkerClaimDueInvocationError> {
        self.claim_due.invoke(CLAIM_DUE_OPERATION, request).await
            .map_err(WorkerClaimDueInvocationError::Runtime)?
            .map_err(WorkerClaimDueInvocationError::Domain)
    }

    pub async fn claim_due_with_context(&self, context: InvocationContext, request: ClaimDueRequest) -> Result<ClaimDueResponse, WorkerClaimDueInvocationError> {
        self.claim_due.invoke_with_context(CLAIM_DUE_OPERATION, context, request).await
            .map_err(WorkerClaimDueInvocationError::Runtime)?
            .map_err(WorkerClaimDueInvocationError::Domain)
    }

    pub async fn expire(&self, request: ExpireRequest) -> Result<ExpireResponse, WorkerExpireInvocationError> {
        self.expire.invoke(EXPIRE_OPERATION, request).await
            .map_err(WorkerExpireInvocationError::Runtime)?
            .map_err(WorkerExpireInvocationError::Domain)
    }

    pub async fn expire_with_context(&self, context: InvocationContext, request: ExpireRequest) -> Result<ExpireResponse, WorkerExpireInvocationError> {
        self.expire.invoke_with_context(EXPIRE_OPERATION, context, request).await
            .map_err(WorkerExpireInvocationError::Runtime)?
            .map_err(WorkerExpireInvocationError::Domain)
    }

    pub async fn process(&self, request: ProcessRequest) -> Result<ProcessResponse, WorkerProcessInvocationError> {
        self.process.invoke(PROCESS_OPERATION, request).await
            .map_err(WorkerProcessInvocationError::Runtime)?
            .map_err(WorkerProcessInvocationError::Domain)
    }

    pub async fn process_with_context(&self, context: InvocationContext, request: ProcessRequest) -> Result<ProcessResponse, WorkerProcessInvocationError> {
        self.process.invoke_with_context(PROCESS_OPERATION, context, request).await
            .map_err(WorkerProcessInvocationError::Runtime)?
            .map_err(WorkerProcessInvocationError::Domain)
    }

    pub async fn retry(&self, request: RetryRequest) -> Result<RetryResponse, WorkerRetryInvocationError> {
        self.retry.invoke(RETRY_OPERATION, request).await
            .map_err(WorkerRetryInvocationError::Runtime)?
            .map_err(WorkerRetryInvocationError::Domain)
    }

    pub async fn retry_with_context(&self, context: InvocationContext, request: RetryRequest) -> Result<RetryResponse, WorkerRetryInvocationError> {
        self.retry.invoke_with_context(RETRY_OPERATION, context, request).await
            .map_err(WorkerRetryInvocationError::Runtime)?
            .map_err(WorkerRetryInvocationError::Domain)
    }
}

impl CapabilityClient for WorkerClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            claim_due: dependencies.one::<WorkerClaimDue>()?,
            expire: dependencies.one::<WorkerExpire>()?,
            process: dependencies.one::<WorkerProcess>()?,
            retry: dependencies.one::<WorkerRetry>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for WorkerClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    claim_due: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<WorkerClaimDue>()?,
                    expire: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<WorkerExpire>()?,
                    process: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<WorkerProcess>()?,
                    retry: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<WorkerRetry>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum WorkerClaimDueInvocationError {
    Domain(ClaimDueError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum WorkerExpireInvocationError {
    Domain(ExpireError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum WorkerProcessInvocationError {
    Domain(ProcessError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum WorkerRetryInvocationError {
    Domain(RetryError),
    Runtime(RuntimeFailure),
}
